@Find_Genre.Server_HostAddress = http://localhost:5213

GET {{Find_Genre.Server_HostAddress}}/genre
Accept: application/json

###
GET {{Find_Genre.Server_HostAddress}}/genre/2
Accept: application/json